name: Deploy Frontend CD

on:
  push:
    branches:
      - desenvolvimento

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing container (if running)
        run: sudo docker stop frontend

      - name: Remove existing container (if exists)
        run: sudo docker rm frontend

      - name: Run Docker container with the new image
        run: sudo docker run --name frontend -p 3000:80 -d ${{ secrets.DOCKERHUB_USER }}/codetech-front:latest