name: CI Frontend React

on:
  pull_request:
    branches: [ desenvolvimento ]
    types: [ opened, reopened ]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ./code-front
          npm cache clean --force
          npm install

      - name: Run tests
        run: npm run test -- --watchAll=false
        working-directory: ./code-front

      - name: Build React app
        run: npm run build
        working-directory: ./code-front
        env:
          CI: false

      - name: Check build output
        run: |
          cd ./code-front
          if [ -d "./build" ]; then
            echo "Build realizado com sucesso!"
          else
            echo "Erro: Diretório de build não encontrado."
            exit 1
          fi

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./code-front
          file: ./code-front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/codetech-front:${{ github.sha }}, ${{ secrets.DOCKERHUB_USER }}/codetech-front:latest